//! Verify Candle's Conv1d against a known reference.
//! Reads npy files generated by Python, runs Candle Conv1d, and compares output.

use candle_core::{Device, Module, Tensor};
use candle_nn::{Conv1d, Conv1dConfig};

const EPS: f32 = 1e-4;
fn manual_conv1d(x: &Tensor, w: &Tensor, b: Option<&Tensor>, pad: usize) -> Tensor {
    // Manual conv1d for verification: [B, C_in, L] * [C_out, C_in, K] → [B, C_out, L]
    let dev = x.device();
    let x_dims = x.dims().to_vec();
    let w_dims = w.dims().to_vec();
    let batch = x_dims[0];
    let c_in = x_dims[1];
    let length = x_dims[2];
    let c_out = w_dims[0];
    let k_size = w_dims[2];
    let l_pad = length + 2 * pad;

    // Pad input
    let x_pad = x.pad_with_zeros(2, pad, pad).unwrap();

    let mut out_data: Vec<f32> = vec![0.0; batch * c_out * length];
    let x_vals: Vec<f32> = x_pad.flatten_all().unwrap().to_vec1().unwrap();
    let w_vals: Vec<f32> = w.flatten_all().unwrap().to_vec1().unwrap();

    // Debug: compute one contribution manually
    let ci0 = 15usize;
    let k0 = 3usize;
    let t0 = 0usize;
    let x_idx_check = ci0 * l_pad + (t0 + k0);
    let w_idx_check = ci0 * k_size + k0;
    let contrib = x_vals[x_idx_check] * w_vals[w_idx_check];
    eprintln!("  [manual dd] ci={ci0},k={k0},t={t0}: x_vals[{x_idx_check}]={:.8} * w_vals[{w_idx_check}]={:.8} = {contrib:.8}",
        x_vals[x_idx_check], w_vals[w_idx_check]);

    // Debug: check padded shape and first few values
    eprintln!("  [manual dd] padded shape: {:?}", x_pad.shape());
    eprintln!("  [manual dd] padded first 10 of channel 0: {:?}", &x_vals[..10]);

    for b_i in 0..batch {
        for co in 0..c_out {
            for t in 0..length {
                let mut sum = 0.0f32;
                for ci in 0..c_in {
                    for k in 0..k_size {
                        let x_idx = b_i * c_in * l_pad + ci * l_pad + (t + k);
                        let w_idx = co * c_in * k_size + ci * k_size + k;
                        sum += x_vals[x_idx] * w_vals[w_idx];
                    }
                }
                let out_idx = b_i * c_out * length + co * length + t;
                out_data[out_idx] = sum;
            }
        }
    }

    // Add bias
    if let Some(b_t) = b {
        let b_vals: Vec<f32> = b_t.flatten_all().unwrap().to_vec1().unwrap();
        for b_i in 0..batch {
            for co in 0..c_out {
                for t in 0..length {
                    let out_idx = b_i * c_out * length + co * length + t;
                    out_data[out_idx] += b_vals[co];
                }
            }
        }
    }

    Tensor::from_vec(out_data, &[batch, c_out, length], dev).unwrap()
}

#[test]
fn check_candle_conv1d() {
    let dev = Device::Cpu;

    // Load reference data
    let weight = Tensor::read_npy("model9_weight_correct.npy").unwrap();
    let bias = Tensor::read_npy("model9_bias.npy").unwrap();
    let input = Tensor::read_npy("model9_test_input.npy").unwrap();
    let expected = Tensor::read_npy("model9_expected_correct.npy").unwrap();

    // Move to CPU
    let weight = weight.to_device(&dev).unwrap();
    let bias = bias.to_device(&dev).unwrap();
    let input = input.to_device(&dev).unwrap();
    let expected = expected.to_device(&dev).unwrap();

    eprintln!(
        "weight: {:?} bias: {:?} input: {:?} expected: {:?}",
        weight.shape(),
        bias.shape(),
        input.shape(),
        expected.shape()
    );

    // ── Verify npy data integrity ──
    let w_flat: Vec<f32> = weight.flatten_all().unwrap().to_vec1().unwrap();
    let i_flat: Vec<f32> = input.flatten_all().unwrap().to_vec1().unwrap();
    let e_flat: Vec<f32> = expected.flatten_all().unwrap().to_vec1().unwrap();
    eprintln!("npy: weight[0..5]={:?} weight[{:?}]={:.8}",
        &w_flat[..5.min(w_flat.len())],
        (w_flat.len()-5.min(w_flat.len()))..w_flat.len(),
        w_flat[w_flat.len()-1]);
    eprintln!("npy: input[0][0][0..5]={:?}", &i_flat[..5]);
    eprintln!("npy: expected[0][0][0..5]={:?}", &e_flat[..5]);
    // Check specific element: weight[0, 15, 3]
    // w_flat index = co * c_in * k_size + ci * k_size + k = 0*32*7 + 15*7 + 3 = 108
    let w_15_3 = w_flat[15 * 7 + 3];
    eprintln!("npy: weight[0,15,3] = {w_15_3:.8}");
    // input[0, 15, 0]: i_flat index = b * c_in * L + ci * L + t = 0*32*13 + 15*13 + 0 = 195
    let i_15_0 = i_flat[15 * 13 + 0];
    eprintln!("npy: input[0,15,0] = {i_15_0:.8}");
    // Expected manual contribution: w[0,15,3] * input[0,15,0] (at t=0, k=3)
    eprintln!("npy: w[0,15,3] * input[0,15,0] = {:.8}", w_15_3 * i_15_0);

    // ── Test 1: Manual conv1d matches Python reference ──
    let manual_out = manual_conv1d(&input, &weight, Some(&bias), 3);
    let manual_v: Vec<f32> = manual_out.flatten_all().unwrap().to_vec1().unwrap();
    eprintln!("manual[0][0][0..5]={:?}", &manual_v[..5]);
    let manual_v: Vec<f32> = manual_out.flatten_all().unwrap().to_vec1().unwrap();
    let expected_v: Vec<f32> = expected.flatten_all().unwrap().to_vec1().unwrap();
    let mut max_diff = 0.0f32;
    for (i, (m, e)) in manual_v.iter().zip(expected_v.iter()).enumerate() {
        let diff = (m - e).abs();
        if diff > max_diff { max_diff = diff; }
    }
    eprintln!("Manual conv vs Python: max_diff = {max_diff:.8}");
    assert!(max_diff < EPS, "Manual conv mismatch: {max_diff:.8}");

    // ── Test 2: Candle Conv1d matches manual conv ──
    let conv = Conv1d::new(
        weight,
        Some(bias),
        Conv1dConfig {
            padding: 3,
            ..Default::default()
        },
    );
    let candle_out = conv.forward(&input).unwrap();
    let candle_v: Vec<f32> = candle_out.flatten_all().unwrap().to_vec1().unwrap();
    let mut max_diff2 = 0.0f32;
    for (i, (c, m)) in candle_v.iter().zip(manual_v.iter()).enumerate() {
        let diff = (c - m).abs();
        if diff > max_diff2 { max_diff2 = diff; }
    }
    eprintln!("Candle Conv1d vs manual: max_diff = {max_diff2:.8}");
    if max_diff2 > EPS {
        eprintln!("FAIL! First 20 values:");
        for i in 0..20.min(candle_v.len()) {
            let cv = candle_v[i];
            let mv = manual_v[i];
            eprintln!("  [{i}] candle={cv:.8} manual={mv:.8} diff={:.8}", (cv - mv).abs());
        }
    }
    assert!(max_diff2 < EPS, "Candle Conv1d mismatch: {max_diff2:.8}");
}
